models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password = db.Column(db.String(120), nullable=False)

users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Email, Length, ValidationError, EqualTo
import re

def validate_data(self, data_field):
    p = re.compile("^(?=.*\d)(?=.*[a-z])\w+$")
    if not p.match(data_field.data):
        raise ValidationError("Must contain at least 1 digit and 1 lowercase character")

def character_check(form,field):
    excluded_chars = "<&%"

    for char in field.data:
        if char in excluded_chars:
            raise ValidationError(f"Character {char} is not allowed.")

class RegisterForm(FlaskForm):
    username = StringField(validators=[DataRequired(), Email(), character_check])
    password = PasswordField(validators=[DataRequired(), Length(min=8, max=15), character_check])
    confirm_password = PasswordField(validators=[DataRequired(), EqualTo('password', message='Both password field must be equal')])
    submit = SubmitField()

app.py
from flask import Flask, render_template
import secrets

app = Flask(__name__)
app.config['SECRET_KEY'] = secrets.token_hex(16)

'''@app.route('/')
def hello_world():
    return render_template('welcome.html', name="Pranish")
'''


from main.views import main_blueprint
app.register_blueprint(main_blueprint)

from users.views import users_blueprint
app.register_blueprint(users_blueprint)

from blog.views import blog_blueprint
app.register_blueprint(blog_blueprint)




if __name__ == '__main__':
    app.run()

blog/views.py
from flask import Blueprint, render_template

blog_blueprint = Blueprint('blog', __name__, template_folder='templates')

@blog_blueprint.route('/blog')
def blog():
    return render_template('blog/blog.html')

main/views.py
from flask import Blueprint, render_template

main_blueprint = Blueprint('main', __name__, template_folder='templates')

@main_blueprint.route('/')
def index():
    return render_template('main/index.html')

users/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from users.forms import RegisterForm

users_blueprint = Blueprint('users', __name__, template_folder='templates')

@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        print(request.form.get('username'))
        print(request.form.get('password'))
        print(request.form.get('confirm_password'))
        return redirect(url_for('user.login'))

    return render_template('users/register.html', form=form)

@users_blueprint.route('/login')
def login():
    return render_template('users/login.html')

welcome/views.py
from flask import Blueprint, render_template
welcome_blueprint = Blueprint('welcome', __name__, template_folder='templates')

@welcome_blueprint.route('/')
def welcome():
    return render_template('base.html')

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CSC2031 Blog</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css"/>
</head>

<body>

<style>
    .table {
        margin-left: auto;
        margin-right: auto;
    }
</style>

<section class="hero is-primary is-fullheight">

    <div class="hero-head">
        <nav class="navbar">
            <div class="container">
                <div id="navbarMenuHeroA" class="navbar-menu">
                    <div class="navbar-end">
                        <a href="{{ url_for('main.index') }}" class="navbar-item">
                            Home
                        </a>
                        <a href="{{ url_for('blog.blog') }}" class="navbar-item">
                            Blog
                        </a>
                        <a href="{{ url_for('users.register') }}" class="navbar-item">
                            Register
                        </a>
                        <a href="{{ url_for('users.login') }}" class="navbar-item">
                            Login
                        </a>
                        <a href="" class="navbar-item">
                            Log out
                        </a>
                    </div>
                </div>
            </div>
        </nav>
    </div>

    <div class="hero-body">
        <div class="container has-text-centered">
            {% block content %}
            {% endblock %}
        </div>
    </div>

</section>
</body>

</html>

templates/blog/blog.html
{% extends 'base.html' %}

{% block content %}
    
    <h1 class="title is-1">blog</h1>

{% endblock %}

templates/main/index.html
{% extends 'base.html' %}

{% block content %}
    
    <h1 class="title is-1">index</h1>

{% endblock %}

templates/users/login.html
{% extends 'base.html' %}

{% block content %}
    
    <h1 class="title is-1">login</h1>

{% endblock %}

templates/users/register.html
{% extends "base.html" %}

{% block content %}

    <div class="column is-5 is-offset-4">
        <h3 class="title is-3">Register</h3>
        <div class="box">
            <form method="POST">
                <div class="field">
                    {{ form.csrf_token() }}
                    <div class="control">
                        {{ form.username(class="input", placeholder="Username") }}
                        {% for error in form.username.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.password(class="input", placeholder="Password") }}
                        {% for error in form.password.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.confirm_password(class="input", placeholder="Confirm Password") }}
                        {% for error in form.confirm_password.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div>
                    {{ form.submit(class="button is-info is-centered") }}
                </div>
            </form>
        </div>
    </div>

{% endblock %}

templates/welcome.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
    <body>
        <h1>Hello, {{ name }}</h1>
    </body>
</html>